name: ${projectName}
description: Players can sit on chairs and everywhere the admin wants them to be able to.
version: ${version}
api-version: '1.19'

main: de.sprax2013.betterchairs.BetterChairsPlugin
depend:
  - Item-NBT-API
softdepend:
  - PlaceholderAPI

author: SpraxDev
authors: [ BlackScarx ]
website: https://github.com/true-og/BetterChairs

commands:
  ${commandName}:
    description: 'Toggle, Reload or Reset BetterChairs'
  toggleChairs:
    description: 'Allows individual players to disabled chairs for them'
    aliases: [ bct ]
    permission: ${permissionBase}.cmd.toggle
  sit:
    description: 'Allows a player to sit on the ground'
    permission: ${permissionBase}.cmd.sit
  dismount:
    description: 'Allows a player to leave a BetterChairs seat'
    permission: ${permissionBase}.cmd.dismount

permissions:
  ${permissionBase}.use:
    description: Allows players to sit on chairs
    default: true
  ${permissionBase}.regeneration:
    description: Grants regeneration to a player when sitting
  ${permissionBase}.cmd.toggle:
    description: Allows individual players to disabled chairs for them
    default: true
  ${permissionBase}.cmd.sit:
    description: Allows a player to sit on the ground
    default: true
  ${permissionBase}.cmd.dismount:
    description: Allows a player to leave a BetterChairs seat
    default: true
  ${permissionBase}.cmd.reset:
    description: Allows admins to eject all players from their chairs
  ${permissionBase}.cmd.reload:
    description: Allows admins to reload the plugin's configuration files
