name: ${pluginName}
description: Players can sit on chairs and everywhere the admin wants them to be able to.
version: ${version}
api-version: '1.19'

main: de.sprax2013.betterchairs.BetterChairsPlugin
softdepend:
  - PlaceholderAPI

author: SpraxDev
authors: [ BlackScarx ]
website: https://github.com/SpraxDev/BetterChairs

commands:
  ${pluginName}:
    description: 'Toggle, Reload or Reset BetterChairs'
  toggleChairs:
    description: 'Allows individual players to disabled chairs for them'
    aliases: [ bct ]
    permission: ${pluginName}.cmd.toggle
  sit:
    description: 'Allows a player to sit on the ground'
    permission: ${pluginName}.cmd.sit

permissions:
  ${pluginName}.use:
    description: Allows players to sit on chairs
    default: true
  ${pluginName}.regeneration:
    description: Grants regeneration to a player when sitting
  ${pluginName}.updater:
    description: Notifies players about updates when joining the server
  ${pluginName}.cmd.toggle:
    description: Allows individual players to disabled chairs for them
    default: true
  ${pluginName}.cmd.sit:
    description: Allows a player to sit on the ground
    default: true
  ${pluginName}.cmd.reset:
    description: Allows admins to eject all players from their chairs
  ${pluginName}.cmd.reload:
    description: Allows admins to reload the plugin's configuration files

